/**
 * The pack file itself (spec §7.3): `.spec-sync/ticket-<nr>.md`.
 *
 * The pack is written for a sub-agent that starts cold. It therefore leads with
 * what it must do (acceptance criteria, gate command), carries the resolved
 * spec sections in full — that is the whole point: no searching — and ends with
 * a machine block. The machine block is what a later `pack` run reads to name
 * file-set overlaps with other open tickets, and what any consumer can use to
 * re-check the section hashes.
 */

import type { PackedSection } from "./spec.js";

export interface PackIssue {
  number: number;
  title: string;
  body: string;
  url?: string;
  labels: string[];
}

export interface CandidateFile {
  path: string;
  /** How the file was found — `named in the issue`, `query:<term>`, `impact:<symbol>`. */
  via: string;
}

export interface Overlap {
  issue: number;
  pack: string;
  files: string[];
}

export interface PackInput {
  issue: PackIssue;
  /** The acceptance-criteria block of the issue body, when it has one. */
  acceptance?: string;
  sections: PackedSection[];
  candidates: CandidateFile[];
  gate: { command: string; profile: string; phases: { name: string; cmd: string }[] };
  overlaps: Overlap[];
  notes: string[];
  generatedAt: string;
}

const MACHINE_MARKER = "<!-- spec-sync:pack -->";

export function packFileName(issue: number): string {
  return `ticket-${issue}.md`;
}

export function renderPack(input: PackInput): string {
  const { issue } = input;
  const lines: string[] = [
    `# Ticket #${issue.number} — ${issue.title}`,
    "",
    `Generated by \`spec-sync pack ${issue.number}\` at ${input.generatedAt}. Do not edit by hand.`,
    "",
    `- Issue: ${issue.url ?? `#${issue.number}`}`,
    `- Labels: ${issue.labels.length === 0 ? "—" : issue.labels.join(", ")}`,
    `- Gate: \`${input.gate.command}\``,
    "",
  ];

  if (input.notes.length > 0) {
    lines.push("> [!NOTE]", ...input.notes.map((note) => `> ${note}`), "");
  }

  lines.push(
    "## Acceptance criteria",
    "",
    input.acceptance ?? "_The issue names no acceptance-criteria block; see the body below._",
    "",
    "## Issue body",
    "",
    issue.body.trim() === "" ? "_empty_" : issue.body.trim(),
    "",
    "## Spec sections (resolved)",
    "",
    "Each section is the effective view, composed from its overlays. `unit@version` and the",
    "section hash are the validity check: re-read the section from the spec-mcp server and",
    "compare the hash before relying on a pack you did not just generate.",
    "",
  );

  for (const section of input.sections) {
    lines.push(
      `### ${section.unit}@${section.version} §${section.heading}`,
      "",
      `- path: \`${section.path}\``,
      `- hash: \`${section.hash}\``,
      `- referenced in the ticket as: §${section.requestedAs}`,
      ...(section.composedFrom === undefined
        ? []
        : [`- composed from: ${section.composedFrom.join(" -> ")}`]),
      "",
      section.content.trim(),
      "",
    );
  }

  lines.push("## Candidate files (CodeGraph impact)", "");
  if (input.candidates.length === 0) {
    lines.push("_None — CodeGraph returned no candidates. Orient yourself before editing._", "");
  } else {
    lines.push(
      ...input.candidates.map((candidate) => `- \`${candidate.path}\` — ${candidate.via}`),
      "",
      "Candidates, not a work order: the ticket decides what is touched.",
      "",
    );
  }

  lines.push("## Gate", "", "```bash", input.gate.command, "```", "");
  if (input.gate.phases.length > 0) {
    lines.push(
      `Profile \`${input.gate.profile}\` runs, in this order:`,
      "",
      ...input.gate.phases.map((phase) => `1. ${phase.name} — \`${phase.cmd}\``),
      "",
    );
  }

  lines.push("## Overlap with other open tickets", "");
  if (input.overlaps.length === 0) {
    lines.push("_No overlap with the file sets of other packed, open tickets._", "");
  } else {
    lines.push(
      "Another open ticket is being built on these files. Coordinate before you touch them:",
      "",
      ...input.overlaps.map(
        (overlap) =>
          `- #${overlap.issue}: ${overlap.files.map((file) => `\`${file}\``).join(", ")}`,
      ),
      "",
    );
  }

  lines.push(
    MACHINE_MARKER,
    "",
    "```json",
    JSON.stringify(machineBlock(input), null, 2),
    "```",
    "",
  );
  return lines.join("\n");
}

interface MachineBlock {
  issue: number;
  generatedAt: string;
  gate: string;
  sections: { unit: string; version: string; path: string; hash: string }[];
  files: string[];
}

function machineBlock(input: PackInput): MachineBlock {
  return {
    issue: input.issue.number,
    generatedAt: input.generatedAt,
    gate: input.gate.command,
    sections: input.sections.map((section) => ({
      unit: section.unit,
      version: section.version,
      path: section.path,
      hash: section.hash,
    })),
    files: input.candidates.map((candidate) => candidate.path),
  };
}

/**
 * Reads the machine block back out of a pack file. Anything unparsable is
 * simply not a pack — a hand-edited or half-written file must not make the next
 * `pack` run fail.
 */
export function readMachineBlock(markdown: string): MachineBlock | undefined {
  const marker = markdown.lastIndexOf(MACHINE_MARKER);
  if (marker === -1) return undefined;
  const fence = /```json\n([\s\S]*?)\n```/u.exec(markdown.slice(marker));
  if (fence?.[1] === undefined) return undefined;

  try {
    const parsed = JSON.parse(fence[1]) as Partial<MachineBlock>;
    if (typeof parsed.issue !== "number" || !Array.isArray(parsed.files)) return undefined;
    return {
      issue: parsed.issue,
      generatedAt: typeof parsed.generatedAt === "string" ? parsed.generatedAt : "",
      gate: typeof parsed.gate === "string" ? parsed.gate : "",
      sections: Array.isArray(parsed.sections) ? parsed.sections : [],
      files: parsed.files.filter((file): file is string => typeof file === "string"),
    };
  } catch {
    return undefined;
  }
}

/**
 * The acceptance-criteria block of an issue body: the heading that names them
 * and everything up to the next heading of the same or a higher level.
 */
export function extractAcceptance(body: string): string | undefined {
  const heading = /^(#{2,4})\s*(?:\d+\.\s*)?(abnahmekriterien|acceptance criteria)\b.*$/imu.exec(
    body,
  );
  if (heading?.index === undefined || heading[1] === undefined) return undefined;

  const level = heading[1].length;
  const rest = body.slice(heading.index + heading[0].length);
  const next = new RegExp(`^#{1,${level}}\\s`, "mu").exec(rest);
  const block = (next?.index === undefined ? rest : rest.slice(0, next.index)).trim();
  return block === "" ? undefined : block;
}
